name: Docker Hub

variables:
- group: Env-Dev

jobs:
- job: docker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub'
      repository: 'felipementel/api.model'
      command: 'login'

  # - task: Bash@3
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       version=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' ./src/API.Model/API.Model.csproj)
  #       echo "tag=$version" >> "$GITHUB_OUTPUT"

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: 'felipementel/api.model'
      dockerfile: './src/API.Model/Dockerfile'
      containerRegistry: 'docker-hub'
      tags: |
        latest

  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub'
      repository: 'felipementel/api.model'
      command: 'buildAndPush'
      Dockerfile: './src/API.Model/Dockerfile'
      tags: |
        felipementel/api.model:latest
